### ISSUE TITLE
How to scroll in honeytalk?

### ISSUE THREAD

**Issue by YoungEii** [clickup/honey#29]

**Comment by b099l3** [comment]
From the [docs](https://github.com/clickup/honey/blob/0ea9555a02eeede691506caa7719ec3de1ba4265/docs/docs/honeytalk.md?plain=1#L50) it shows you can do this:


## Swipe
The swipe action will try to find the specified target widget and issue a swipe event. All widgets can be tapped regardless of their type or Semantics configuration. You can use "swipe", "slide" and "scroll" interchangeably.

There are 4 types of swipe `left` (default), `right` , `up` , `down`

You have to specify how many points / how long swipe should be by using 
`by {number}`  notation 

Example:
swipe left "Today" by 300

**Comment by YoungEii** [comment]
Thanks, @b099l3 ~
